language: node_js
node_js:
- 10.15.1
branches:
  only:
  - source
before_install:
- npm install -g hexo-cli
- npm install --save hexo-deployer-git
install:
- npm install
script:
- hexo generate
after_success:
- git config --global user.name "evanljp"
- git config --global user.email "evanljp@outlook.com"
- sed -i'' "s~git@github.com:EvanLjp/evanljp.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/EvanLjp/evanljp.github.io.git~" _config.yml
- hexo deploy --silent
env:
  global:
    secure: fuY23T6wEurOWPseTP8Ouh4i+5fQk/0+SL98J7dkPpisXYFl36tmPxyviT5Ho2DiANcrpnkNMPgjINmIfWhv5HOqWOcQLUDUQBfujpHfvR/1CcnW5cRhFjkxEKV+09MCR58asl6Q+BPhGIjojHsGRbT5mT1Gsy+cJmXmrXqzo6hI0bDldexxF/3vdVUjgAe8YxHFswX8CfWt6ldHxRpR1S58c9dING6bT2VdlYkVoqAB5pKzVrSagg0FohR+ezClu2y9qEYTpxpe3vz1KOPsKooT7HZhsamMvJRC5VArL7syZE7BSMzYOjEM+26x/ZymsFJoj3/A5CY1RApm2JMc61SxfUfhAjF78qB5H6x6CPU2+tQtHbCymGZtqGgGHEF+R5kCvLF+RI3EkuONoGoV/8MO+LKwtMMXq7B92kVxSGURlQm17i6z2CnC7vZ2smasWGkMhL8nCl7Tu9v/GoqtTyiyBA2BUdQM/OiQWi2ddJUzwf/x3//kk65tP13WYN0qQDK7LmL3xaxvyDLRmBraS7cQ0yAlTTwBhLJi5O0hlvVZA1SpjG2Ay3xryyoU3STFkfNQFMGYsyVOoahF6GxL3neRL0I7YttCodjfIwXGF06zQh3rSEtb5Xn+QQ7yPaG8j0QcxuzxcPfsrcfUq//dUGG8WGpgxo+caOtsGgY9Zcw=
